### ISSUE TITLE
Data Export URL not available

### ISSUE THREAD

**Issue by xpac1985** [plusplusslack/pluspl.us#197]
**Describe the bug**
The export URL provided by plusplus is not available.

**To Reproduce**
1. Say `@pluspl.us export`
2. Click on provided link
3. Notice that the link (https://pluspl.us/archive/something.csv) is not available due to pluspl.us not having an A or AAAA record.

**Expected behavior**
Being able to download export CSV.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/6882771/129716176-461fbe0f-c922-4ca8-9067-6da8c3c74907.png)

**Comment by xpac1985** [comment]
Just noticed:
Replacing https://pluspl.us with https://plusplusserver.herokuapp.com and the download works fine.

**Comment by Conway** [comment]
Thanks for the report, this should be fixed now
